repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks
        name: "🔒 Security - Detect hardcoded secrets"

  - repo: https://github.com/crate-ci/typos
    rev: v1.33.1
    hooks:
      - id: typos
        name: "📜 Spell Check - Detect common typos in code and comments"
