name: Initialize Repository

on:
 #create:
  workflow_dispatch:

env:
  TF_VAR_github_organization: ${{ github.repository_owner }}
  TF_VAR_github_token: ${{ secrets.ACCESS_TOKEN }}
  TF_VAR_current_repository: ${{ github.repository }}

defaults:
  run:
    working-directory: OpenTofu

jobs:
  init-repository:
    runs-on: ubuntu-latest
    name: Initialize Repository

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check

      - name: OpenTofu init
        id: init
        run: tofu init

      - name: OpenTofu validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu plan
        id: plan
        run: tofu plan -no-color

      - name: OpenTofu apply
        id: apply
        run: tofu apply -auto-approve