name: Secrets Scanner

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Every day at 02:00

jobs:
  scan:
    name: Secrets Scan with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Required as this is used inside an Organization